### ISSUE TITLE
Neptune DB version and instance type error

### ISSUE THREAD

**Issue by chetanagrawal** [aws/aws-connected-device-framework#71] opened 2022-04-08 05:11 UTC
While deploying the CDF stack its observed that AssetLibrary stack fails to create due to Neptune DB error where the Neptune DB version is not supported with the r4.xlarge instance type (Default instance type).

**Comment by jonasneu-aws** [comment] 2022-04-08 16:38
Hi @chetanagrawal, thank you for reporting this! The root cause of the behavior you are seeing is that [new version of Amazon Neptune are not compatible with r4 instance types](https://docs.aws.amazon.com/neptune/latest/userguide/engine-releases-1.1.0.0.html) and that r4 instance types are generally no longer available for new instance launches.

[CDF version 1.0.10](https://github.com/aws/aws-connected-device-framework/releases/tag/1.0.10) addressed this by: 

* relaxing the validation rules for Neptune instance types to be a regex instead of a fixed list of instance types (which would inevitable become outdated over time)
* updating the CDF installer wizard (the `cdf-cli deploy` command) to present a list of currently available instance types for selection
* changing the default to r5.xlarge

If you are setting up a new CDF deployment with the latest version, you should automatically be guided to a working default. 

If you use an older version or have an existing configuration file, you can manually update the instance type. Note that updating the instance type of a Neptune instance will result in downtime, detailed documentation on managing instances is available [here](https://docs.aws.amazon.com/neptune/latest/userguide/manage-console-instances-modify.html).

**Comment by williamsia** [comment] 2022-06-27 11:25
Hi @chetanagrawal , as @jonasneu-aws  had mentioned this is fixed in version 1.0.10, but I will close this issue, but do let us know if this fix does not address your issue. Thanks again for raising the issue.

**Closed by williamsia** 2022-06-27 11:25 UTC
